### ISSUE TITLE
Add vm only tags

### ISSUE THREAD

**Issue by stiross79** [equinor/terraform-azurerm-vm#13]
We need to add a WBS code to all resources for billing purposes, but we also have operational tags that should only be added to the virtual machine resource itself.

### Variables
```tf
variable "vm_tags" {
  description = "A map of tags to be assigned to the virtual machine resource only."
  type        = map(string)
  default     = {}
}
```

### Virtual Machine Resources
```tf
# Merge the vm_only_tags and the tags variables
tags = merge(var.vm_tags, var.tags)
```

**Comment by hknutsen** [comment]
I propose a variable name `vm_tags` to follow our naming convention.

**Comment by stiross79** [comment]
Purposed changes has now been updated with the `vm_tags` name.
