### ISSUE TITLE
Add the possibility of creating backup

### ISSUE THREAD

**Issue by stiross79** [equinor/terraform-azurerm-vm#18]
Add the possibility of creating backup on this virtual machine.

### Variables
```tf
variable "backup" {
  description = "Should a backup be created for this virtual machine"
  type = object({
    recovery_service_vault_name = string
    backup_policy_id            = string
    resource_group_name         = optional(string, "")
  })
  default = null
}
```

### Virtual Machine Resources
```tf
resource "azurerm_backup_protected_vm" "vm" {
  count               = var.backup != null ? 1 : 0
  resource_group_name = coalesce(var.backup.resource_group_name, var.resource_group_name)
  recovery_vault_name = var.backup.recovery_service_vault_name
  source_vm_id = (
    var.kind == "Linux" ? azurerm_linux_virtual_machine.this[0].id : azurerm_windows_virtual_machine.this[0].id
  )
  backup_policy_id = var.backup.backup_policy_id
}
```

**Comment by hknutsen** [comment]
Since enabling backup of the VM requires the creation of an **optional resource**, I propose creating said resource outside of this module:

```terraform
module "vm" {
  source = "equinor/vm/azurerm"

  # omitted
}

resource "azurerm_backup_protected_vm" "example" {
  resource_group_name = "<RESOURCE_GROUP_NAME>"
  recovery_vault_name = "<RECOVERY_VAULT_NAME>"
  source_vm_id        = module.vm.vm_id
  backup_policy_id    = "<BACKUP_POLICY_ID>"
}
```

**Comment by stiross79** [comment]
That is a possibility, but the `azurerm_backup_protected_vm` can only be used with an Azure virtual machine, so I thought having it as part of the virtual machine module would be convenient. it also makes the resource naming better and neatly placed together when you run `terraform state list`.

```tf
module.myvm.azurerm_linux_virtual_machine.this[0]
module.myvm.azurerm_backup_protected_vm.vm[0]
```

**Comment by hknutsen** [comment]
To me, the `azurerm_backup_protected_vm` resource looks like it would belong in a potential `backup` module instead, since it's a resource related to the Azure Backup service.

**Comment by stiross79** [comment]
Ok. We can remove it from the VM module and create the resource somewhere else.

**Comment by hknutsen** [comment]
If you wrap this VM module in some "service" module, you could always add the `azurerm_backup_protected_vm` resource there 🙂
