### ISSUE TITLE
add nsg_group_id parameter to ip_configurations

### ISSUE THREAD

**Issue by stiross79** [equinor/terraform-azurerm-vm#32]
We should have the possibility to assign a Network Security Group to network interfaces.

### Variables
```tf
variable "network_interfaces" {
...
    nsg_id = optional(string)
...
}
```

### Main
```tf
resource "azurerm_network_interface_security_group_association" "this" {
  for_each = {
    for k, v in var.network_interfaces : k => v if v.nsg_id != null
  }
  network_interface_id      = azurerm_network_interface.this[each.key]
  network_security_group_id = each.value.nsg_id
}
```

**Comment by hknutsen** [comment]
We shouldn't create conditionals on values that sometimes are unknown until the apply step.

Should wrap the NSG ID in an object, similar to how we do with subnets in the network module: https://github.com/equinor/terraform-azurerm-network/blob/2a45cc3eb667418ed7a98e1290dd9bd6c242756b/variables.tf#L34-L36

**Comment by stiross79** [comment]
@hknutsen Do you think we should define the NSG association outside of the VM module ?
